DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS room;

CREATE TABLE user
(
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL
);

CREATE TABLE room
(
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    created  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    room_key TEXT      NOT NULL
);