# Generated by Django 3.2 on 2021-05-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('player_id', models.TextField(unique=True)),
                ('score', models.IntegerField(default=None)),
                ('timestamp', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Outstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('player_id', models.TextField()),
                ('task_archetype', models.TextField()),
                ('timestamp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('player_id', models.TextField()),
                ('task_archetype', models.TextField()),
                ('task_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('player_id', models.TextField()),
                ('task_archetype', models.TextField()),
                ('task_name', models.TextField()),
            ],
        ),
    ]
