# Generated by Django 3.2 on 2021-05-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('player_id', models.TextField()),
                ('task_archetype', models.TextField()),
                ('goal', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('timestamp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('player_id', models.TextField()),
                ('number_of_players', models.IntegerField(default=2)),
                ('score', models.IntegerField(default=0, null=True)),
                ('round_num', models.IntegerField(default=0, null=True)),
                ('timestamp', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('speaker_player_id', models.TextField()),
                ('listener_player_id', models.TextField()),
                ('task_archetype', models.TextField()),
                ('task_name', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskNameMappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('player_id', models.TextField()),
                ('task_archetype', models.TextField()),
                ('task_name', models.TextField()),
            ],
        ),
    ]
