# Generated by Django 3.2 on 2021-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='number_of_players',
        ),
        migrations.AddField(
            model_name='games',
            name='esp_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='num_players',
            field=models.IntegerField(default=0),
        ),
    ]
