# Generated by Django 3.2 on 2021-05-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('player_id', models.TextField()),
                ('task_archetype', models.TextField()),
                ('goal', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('timestamp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('player_id', models.TextField(unique=True)),
                ('score', models.IntegerField(default=None)),
                ('round_num', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('speaker_player_id', models.TextField()),
                ('listener_player_id', models.TextField()),
                ('task_archetype', models.TextField()),
                ('task_name', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='TaskAssignment',
            new_name='TaskNameMappings',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Outstanding',
        ),
        migrations.DeleteModel(
            name='TaskName',
        ),
    ]
