# Generated by Django 3.2 on 2021-05-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210503_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
