# Generated by Django 3.2 on 2021-05-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_games_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='round_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
