# Generated by Django 3.2 on 2021-05-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210503_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='number_of_players',
            field=models.IntegerField(default=2),
        ),
    ]
